[build-system]
requires = ['setuptools', 'setuptools_scm', 'wheel']
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 80
target-version = ['py36']
skip-string-normalization = true
exclude = '^/build/.*$'
